package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/templatedop/neworm/internal/config"
	"github.com/templatedop/neworm/internal/introspect"
)

// Generator generates Go code from database schema
type Generator struct {
	schema      *introspect.Schema
	outputDir   string
	packageName string
	config      *config.Config
}

// New creates a new Generator
func New(schema *introspect.Schema, outputDir, packageName string) *Generator {
	return &Generator{
		schema:      schema,
		outputDir:   outputDir,
		packageName: packageName,
	}
}

// NewWithConfig creates a new Generator with configuration
func NewWithConfig(schema *introspect.Schema, cfg *config.Config) *Generator {
	return &Generator{
		schema:      schema,
		outputDir:   cfg.Generation.OutputDir,
		packageName: cfg.Generation.PackageName,
		config:      cfg,
	}
}

// Generate generates all code files
func (g *Generator) Generate() error {
	if err := os.MkdirAll(g.outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Generate models
	if err := g.generateModels(); err != nil {
		return fmt.Errorf("failed to generate models: %w", err)
	}

	// Generate query builders
	if err := g.generateQueryBuilders(); err != nil {
		return fmt.Errorf("failed to generate query builders: %w", err)
	}

	// Generate client
	if err := g.generateClient(); err != nil {
		return fmt.Errorf("failed to generate client: %w", err)
	}

	// Generate predicates
	if err := g.generatePredicates(); err != nil {
		return fmt.Errorf("failed to generate predicates: %w", err)
	}

	// Generate custom queries from config
	if g.config != nil && len(g.config.Queries) > 0 {
		if err := g.generateCustomQueries(); err != nil {
			return fmt.Errorf("failed to generate custom queries: %w", err)
		}
	}

	return nil
}

func (g *Generator) generateModels() error {
	for _, table := range g.schema.Tables {
		if err := g.generateModel(table); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateModel(table *introspect.Table) error {
	data := map[string]interface{}{
		"Package":   g.packageName,
		"Table":     table,
		"ModelName": toModelName(table.Name),
		"Columns":   table.Columns,
	}

	tmpl := `// Code generated by neworm. DO NOT EDIT.
package {{ .Package }}

import (
	"time"
	{{ if hasUUID .Columns }}"github.com/google/uuid"{{ end }}
)

// {{ .ModelName }} represents a row in the {{ .Table.Name }} table
type {{ .ModelName }} struct {
	{{ range .Columns }}{{ toFieldName .Name }} {{ .GoType }} ` + "`json:\"{{ .Name }}\"`" + `
	{{ end }}
}

// TableName returns the table name
func ({{ toLower (slice .ModelName 0 1) }} *{{ .ModelName }}) TableName() string {
	return "{{ .Table.Name }}"
}
`

	return g.executeTemplate("model", table.Name+".go", tmpl, data)
}

func (g *Generator) generateQueryBuilders() error {
	for _, table := range g.schema.Tables {
		if err := g.generateQueryBuilder(table); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generateQueryBuilder(table *introspect.Table) error {
	modelName := toModelName(table.Name)

	// Build relationship info
	relationships := g.buildRelationships(table)

	data := map[string]interface{}{
		"Package":       g.packageName,
		"Table":         table,
		"ModelName":     modelName,
		"QueryName":     modelName + "Query",
		"BuilderName":   modelName + "QueryBuilder",
		"Columns":       table.Columns,
		"Relationships": relationships,
	}

	tmpl := `// Code generated by neworm. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"fmt"
	"strings"

	"github.com/templatedop/neworm/runtime"
)

// {{ .QueryName }} is the query builder for {{ .ModelName }}
type {{ .QueryName }} struct {
	client     *Client
	predicates []runtime.Predicate
	order      []string
	limitVal   *int
	offsetVal  *int
	withFKs    map[string]*queryConfig
}

type queryConfig struct {
	modifier func(runtime.Query)
}

// Query creates a new query builder
func (c *{{ .ModelName }}Client) Query() *{{ .QueryName }} {
	return &{{ .QueryName }}{
		client:  c.client,
		withFKs: make(map[string]*queryConfig),
	}
}

// Where adds a predicate to the query
func (q *{{ .QueryName }}) Where(predicates ...runtime.Predicate) *{{ .QueryName }} {
	q.predicates = append(q.predicates, predicates...)
	return q
}

// Order adds an ORDER BY clause
func (q *{{ .QueryName }}) Order(fields ...string) *{{ .QueryName }} {
	q.order = append(q.order, fields...)
	return q
}

// Limit sets the LIMIT clause
func (q *{{ .QueryName }}) Limit(limit int) *{{ .QueryName }} {
	q.limitVal = &limit
	return q
}

// Offset sets the OFFSET clause
func (q *{{ .QueryName }}) Offset(offset int) *{{ .QueryName }} {
	q.offsetVal = &offset
	return q
}

{{ range .Relationships }}
// With{{ .MethodName }} loads the {{ .TargetModel }} relationship
func (q *{{ $.QueryName }}) With{{ .MethodName }}(opts ...func(*{{ .TargetModel }}Query)) *{{ $.QueryName }} {
	var modifier func(runtime.Query)
	if len(opts) > 0 {
		modifier = func(query runtime.Query) {
			opts[0](query.(*{{ .TargetModel }}Query))
		}
	}
	q.withFKs["{{ .FieldName }}"] = &queryConfig{modifier: modifier}
	return q
}

// Has{{ .MethodName }} adds a predicate to check if the relationship exists
func (q *{{ $.QueryName }}) Has{{ .MethodName }}() *{{ $.QueryName }} {
	q.predicates = append(q.predicates, runtime.HasEdge("{{ .FieldName }}"))
	return q
}

// Has{{ .MethodName }}With adds a predicate to filter by the relationship
func (q *{{ $.QueryName }}) Has{{ .MethodName }}With(predicates ...runtime.Predicate) *{{ $.QueryName }} {
	q.predicates = append(q.predicates, runtime.HasEdgeWith("{{ .FieldName }}", predicates...))
	return q
}
{{ end }}

// All executes the query and returns all results
func (q *{{ .QueryName }}) All(ctx context.Context) ([]*{{ .ModelName }}, error) {
	query := q.buildQuery()
	rows, err := q.client.db.Query(ctx, query, q.buildArgs()...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*{{ .ModelName }}
	for rows.Next() {
		var m {{ .ModelName }}
		if err := rows.Scan({{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}&m.{{ toFieldName $col.Name }}{{ end }}); err != nil {
			return nil, err
		}
		results = append(results, &m)
	}

	// Load relationships if requested
	if err := q.loadRelationships(ctx, results); err != nil {
		return nil, err
	}

	return results, rows.Err()
}

// First executes the query and returns the first result
func (q *{{ .QueryName }}) First(ctx context.Context) (*{{ .ModelName }}, error) {
	q.Limit(1)
	results, err := q.All(ctx)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return nil, fmt.Errorf("no rows found")
	}
	return results[0], nil
}

// Count returns the count of records
func (q *{{ .QueryName }}) Count(ctx context.Context) (int64, error) {
	query := q.buildCountQuery()
	var count int64
	err := q.client.db.QueryRow(ctx, query, q.buildArgs()...).Scan(&count)
	return count, err
}

func (q *{{ .QueryName }}) buildQuery() string {
	var parts []string
	parts = append(parts, "SELECT {{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}{{ $col.Name }}{{ end }}")
	parts = append(parts, "FROM {{ .Table.Name }}")

	if len(q.predicates) > 0 {
		parts = append(parts, "WHERE "+q.buildWhere())
	}

	if len(q.order) > 0 {
		parts = append(parts, "ORDER BY "+strings.Join(q.order, ", "))
	}

	if q.limitVal != nil {
		parts = append(parts, fmt.Sprintf("LIMIT %d", *q.limitVal))
	}

	if q.offsetVal != nil {
		parts = append(parts, fmt.Sprintf("OFFSET %d", *q.offsetVal))
	}

	return strings.Join(parts, " ")
}

func (q *{{ .QueryName }}) buildCountQuery() string {
	var parts []string
	parts = append(parts, "SELECT COUNT(*)")
	parts = append(parts, "FROM {{ .Table.Name }}")

	if len(q.predicates) > 0 {
		parts = append(parts, "WHERE "+q.buildWhere())
	}

	return strings.Join(parts, " ")
}

func (q *{{ .QueryName }}) buildWhere() string {
	var conditions []string
	for _, p := range q.predicates {
		conditions = append(conditions, p.String())
	}
	return strings.Join(conditions, " AND ")
}

func (q *{{ .QueryName }}) buildArgs() []interface{} {
	var args []interface{}
	for _, p := range q.predicates {
		args = append(args, p.Args()...)
	}
	return args
}

func (q *{{ .QueryName }}) loadRelationships(ctx context.Context, models []*{{ .ModelName }}) error {
	// TODO: Implement relationship loading
	return nil
}
`

	return g.executeTemplate("query", table.Name+"_query.go", tmpl, data)
}

func (g *Generator) generateClient() error {
	data := map[string]interface{}{
		"Package": g.packageName,
		"Tables":  g.schema.Tables,
	}

	tmpl := `// Code generated by neworm. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/templatedop/neworm/runtime"
)

// Client is the database client
type Client struct {
	db *pgxpool.Pool
	{{ range .Tables }}{{ toModelName .Name }} *{{ toModelName .Name }}Client
	{{ end }}
}

// NewClient creates a new database client
func NewClient(db *pgxpool.Pool) *Client {
	c := &Client{db: db}
	{{ range .Tables }}c.{{ toModelName .Name }} = &{{ toModelName .Name }}Client{client: c}
	{{ end }}
	return c
}

// Close closes the database connection
func (c *Client) Close() {
	c.db.Close()
}

// NewBatch creates a new batch operation
func (c *Client) NewBatch() *Batch {
	return &Batch{
		client: c,
		batch:  runtime.NewBatch(c.db),
		{{ range .Tables }}{{ toLower (slice (toModelName .Name) 0 1) }}{{ slice (toModelName .Name) 1 (len (toModelName .Name)) }}: &{{ toModelName .Name }}Batch{},
		{{ end }}
	}
}

// Batch represents a batch of operations
type Batch struct {
	client *Client
	batch  *runtime.Batch
	{{ range .Tables }}{{ toModelName .Name }} *{{ toModelName .Name }}Batch
	{{ end }}
}

// Send executes the batch
func (b *Batch) Send(ctx context.Context) error {
	// Queue all operations
	{{ range .Tables }}
	for _, m := range b.{{ toModelName .Name }}.creates {
		b.batch.Queue(` + "`" + `INSERT INTO {{ .Name }} ({{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}{{ $col.Name }}{{ end }}) VALUES ({{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}${{ add $i 1 }}{{ end }})` + "`" + `,
			{{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $col.Name }}{{ end }})
	}
	for _, m := range b.{{ toModelName .Name }}.updates {
		{{ if hasPK . }}
		b.batch.Queue(` + "`" + `UPDATE {{ .Name }} SET {{ range $i, $col := .Columns }}{{ if not $col.IsPrimaryKey }}{{ if $i }}, {{ end }}{{ $col.Name }} = ${{ add $i 1 }}{{ end }}{{ end }} WHERE {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }} AND {{ end }}{{ $pk }} = ${{ add (len $.Columns) (add $i 1) }}{{ end }}` + "`" + `,
			{{ range $i, $col := .Columns }}{{ if not $col.IsPrimaryKey }}m.{{ toFieldName $col.Name }}, {{ end }}{{ end }}{{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $pk }}{{ end }})
		{{ end }}
	}
	for _, m := range b.{{ toModelName .Name }}.deletes {
		{{ if hasPK . }}
		b.batch.Queue(` + "`" + `DELETE FROM {{ .Name }} WHERE {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }} AND {{ end }}{{ $pk }} = ${{ add $i 1 }}{{ end }}` + "`" + `,
			{{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $pk }}{{ end }})
		{{ end }}
	}
	{{ end }}

	// Execute batch
	results, err := b.batch.Send(ctx)
	if err != nil {
		return err
	}
	return results.Close()
}

{{ range .Tables }}
// {{ toModelName .Name }}Client is the client for {{ .Name }} table
type {{ toModelName .Name }}Client struct {
	client *Client
}

// Create inserts a new {{ toModelName .Name }}
func (c *{{ toModelName .Name }}Client) Create(ctx context.Context, m *{{ toModelName .Name }}) error {
	query := ` + "`" + `INSERT INTO {{ .Name }} ({{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}{{ $col.Name }}{{ end }})
		VALUES ({{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}${{ add $i 1 }}{{ end }})
		{{ if hasPK . }}RETURNING {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}{{ $pk }}{{ end }}{{ end }}` + "`" + `

	{{ if hasPK . }}
	err := c.client.db.QueryRow(ctx, query, {{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $col.Name }}{{ end }}).Scan({{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}&m.{{ toFieldName $pk }}{{ end }})
	{{ else }}
	_, err := c.client.db.Exec(ctx, query, {{ range $i, $col := .Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $col.Name }}{{ end }})
	{{ end }}
	return err
}

// CreateMany inserts multiple {{ toModelName .Name }} records
func (c *{{ toModelName .Name }}Client) CreateMany(ctx context.Context, models []*{{ toModelName .Name }}) error {
	if len(models) == 0 {
		return nil
	}

	batch := c.client.NewBatch()
	for _, m := range models {
		batch.{{ toModelName .Name }}.Create(m)
	}
	return batch.Send(ctx)
}

// Update updates a {{ toModelName .Name }}
func (c *{{ toModelName .Name }}Client) Update(ctx context.Context, m *{{ toModelName .Name }}) error {
	{{ if hasPK . }}
	query := ` + "`" + `UPDATE {{ .Name }} SET {{ range $i, $col := .Columns }}{{ if not $col.IsPrimaryKey }}{{ if $i }}, {{ end }}{{ $col.Name }} = ${{ add $i 1 }}{{ end }}{{ end }}
		WHERE {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }} AND {{ end }}{{ $pk }} = ${{ add (len $.Columns) (add $i 1) }}{{ end }}` + "`" + `

	_, err := c.client.db.Exec(ctx, query,
		{{ range $i, $col := .Columns }}{{ if not $col.IsPrimaryKey }}m.{{ toFieldName $col.Name }}, {{ end }}{{ end }}
		{{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $pk }}{{ end }})
	return err
	{{ else }}
	return fmt.Errorf("table {{ .Name }} has no primary key, cannot update")
	{{ end }}
}

// Delete deletes a {{ toModelName .Name }}
func (c *{{ toModelName .Name }}Client) Delete(ctx context.Context, m *{{ toModelName .Name }}) error {
	{{ if hasPK . }}
	query := ` + "`" + `DELETE FROM {{ .Name }} WHERE {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }} AND {{ end }}{{ $pk }} = ${{ add $i 1 }}{{ end }}` + "`" + `
	_, err := c.client.db.Exec(ctx, query, {{ range $i, $pk := .PrimaryKey.Columns }}{{ if $i }}, {{ end }}m.{{ toFieldName $pk }}{{ end }})
	return err
	{{ else }}
	return fmt.Errorf("table {{ .Name }} has no primary key, cannot delete")
	{{ end }}
}

// {{ toModelName .Name }}Batch provides batch operations for {{ toModelName .Name }}
type {{ toModelName .Name }}Batch struct {
	creates []*{{ toModelName .Name }}
	updates []*{{ toModelName .Name }}
	deletes []*{{ toModelName .Name }}
}

// Create adds a create operation to the batch
func (b *{{ toModelName .Name }}Batch) Create(m *{{ toModelName .Name }}) {
	b.creates = append(b.creates, m)
}

// Update adds an update operation to the batch
func (b *{{ toModelName .Name }}Batch) Update(m *{{ toModelName .Name }}) {
	b.updates = append(b.updates, m)
}

// Delete adds a delete operation to the batch
func (b *{{ toModelName .Name }}Batch) Delete(m *{{ toModelName .Name }}) {
	b.deletes = append(b.deletes, m)
}
{{ end }}
`

	return g.executeTemplate("client", "client.go", tmpl, data)
}

func (g *Generator) generatePredicates() error {
	for _, table := range g.schema.Tables {
		if err := g.generatePredicate(table); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generatePredicate(table *introspect.Table) error {
	modelName := toModelName(table.Name)
	packageName := strings.ToLower(modelName)

	data := map[string]interface{}{
		"Package":     packageName,
		"ModelName":   modelName,
		"Table":       table,
		"Columns":     table.Columns,
		"ParentPkg":   g.packageName,
	}

	// Create package directory
	pkgDir := filepath.Join(g.outputDir, packageName)
	if err := os.MkdirAll(pkgDir, 0755); err != nil {
		return err
	}

	tmpl := `// Code generated by neworm. DO NOT EDIT.
package {{ .Package }}

import (
	"github.com/templatedop/neworm/runtime"
)

// Field names
const (
	{{ range .Columns }}Field{{ toFieldName .Name }} = "{{ .Name }}"
	{{ end }}
)

{{ range .Columns }}
// {{ toFieldName .Name }} provides field operations for {{ .Name }}
var {{ toFieldName .Name }} = &{{ toFieldName .Name }}Field{}

type {{ toFieldName .Name }}Field struct{}

// Equals creates a predicate for {{ .Name }} = value
func (f *{{ toFieldName .Name }}Field) Equals(value {{ .GoType }}) runtime.Predicate {
	return runtime.EQ("{{ .Name }}", value)
}

// NotEquals creates a predicate for {{ .Name }} != value
func (f *{{ toFieldName .Name }}Field) NotEquals(value {{ .GoType }}) runtime.Predicate {
	return runtime.NEQ("{{ .Name }}", value)
}

{{ if or (eq .GoType "int32") (eq .GoType "int64") (eq .GoType "float64") }}
// GreaterThan creates a predicate for {{ .Name }} > value
func (f *{{ toFieldName .Name }}Field) GreaterThan(value {{ .GoType }}) runtime.Predicate {
	return runtime.GT("{{ .Name }}", value)
}

// GreaterThanOrEqual creates a predicate for {{ .Name }} >= value
func (f *{{ toFieldName .Name }}Field) GreaterThanOrEqual(value {{ .GoType }}) runtime.Predicate {
	return runtime.GTE("{{ .Name }}", value)
}

// LessThan creates a predicate for {{ .Name }} < value
func (f *{{ toFieldName .Name }}Field) LessThan(value {{ .GoType }}) runtime.Predicate {
	return runtime.LT("{{ .Name }}", value)
}

// LessThanOrEqual creates a predicate for {{ .Name }} <= value
func (f *{{ toFieldName .Name }}Field) LessThanOrEqual(value {{ .GoType }}) runtime.Predicate {
	return runtime.LTE("{{ .Name }}", value)
}
{{ end }}

{{ if eq .GoType "string" }}
// Contains creates a predicate for {{ .Name }} LIKE %value%
func (f *{{ toFieldName .Name }}Field) Contains(value string) runtime.Predicate {
	return runtime.Contains("{{ .Name }}", value)
}

// HasPrefix creates a predicate for {{ .Name }} LIKE value%
func (f *{{ toFieldName .Name }}Field) HasPrefix(value string) runtime.Predicate {
	return runtime.HasPrefix("{{ .Name }}", value)
}

// HasSuffix creates a predicate for {{ .Name }} LIKE %value
func (f *{{ toFieldName .Name }}Field) HasSuffix(value string) runtime.Predicate {
	return runtime.HasSuffix("{{ .Name }}", value)
}
{{ end }}

// In creates a predicate for {{ .Name }} IN (values...)
func (f *{{ toFieldName .Name }}Field) In(values ...{{ .GoType }}) runtime.Predicate {
	ifaces := make([]interface{}, len(values))
	for i, v := range values {
		ifaces[i] = v
	}
	return runtime.In("{{ .Name }}", ifaces...)
}

// NotIn creates a predicate for {{ .Name }} NOT IN (values...)
func (f *{{ toFieldName .Name }}Field) NotIn(values ...{{ .GoType }}) runtime.Predicate {
	ifaces := make([]interface{}, len(values))
	for i, v := range values {
		ifaces[i] = v
	}
	return runtime.NotIn("{{ .Name }}", ifaces...)
}

{{ if .IsNullable }}
// IsNull creates a predicate for {{ .Name }} IS NULL
func (f *{{ toFieldName .Name }}Field) IsNull() runtime.Predicate {
	return runtime.IsNull("{{ .Name }}")
}

// IsNotNull creates a predicate for {{ .Name }} IS NOT NULL
func (f *{{ toFieldName .Name }}Field) IsNotNull() runtime.Predicate {
	return runtime.NotNull("{{ .Name }}")
}
{{ end }}
{{ end }}
`

	return g.executeTemplateToDir(pkgDir, "predicate", packageName+".go", tmpl, data)
}

type Relationship struct {
	MethodName  string
	FieldName   string
	TargetModel string
	TargetTable string
	IsOneToMany bool
	FKColumns   []string
}

func (g *Generator) buildRelationships(table *introspect.Table) []Relationship {
	var relationships []Relationship

	// Foreign keys from this table (many-to-one or one-to-one)
	for _, fk := range table.ForeignKeys {
		rel := Relationship{
			MethodName:  toModelName(fk.RefTableName),
			FieldName:   strings.ToLower(toModelName(fk.RefTableName)),
			TargetModel: toModelName(fk.RefTableName),
			TargetTable: fk.RefTableName,
			IsOneToMany: false,
			FKColumns:   fk.ColumnNames,
		}
		relationships = append(relationships, rel)
	}

	// Inverse relationships (one-to-many)
	for _, otherTable := range g.schema.Tables {
		if otherTable.Name == table.Name {
			continue
		}
		for _, fk := range otherTable.ForeignKeys {
			if fk.RefTableName == table.Name {
				rel := Relationship{
					MethodName:  pluralize(toModelName(otherTable.Name)),
					FieldName:   strings.ToLower(pluralize(toModelName(otherTable.Name))),
					TargetModel: toModelName(otherTable.Name),
					TargetTable: otherTable.Name,
					IsOneToMany: true,
					FKColumns:   fk.ColumnNames,
				}
				relationships = append(relationships, rel)
			}
		}
	}

	return relationships
}

func (g *Generator) generateCustomQueries() error {
	if len(g.config.Queries) == 0 {
		return nil
	}

	data := map[string]interface{}{
		"Package": g.packageName,
		"Queries": g.config.Queries,
	}

	tmpl := `// Code generated by neworm. DO NOT EDIT.
package {{ .Package }}

import (
	"context"
	"fmt"
)

{{ range .Queries }}
// {{ .Name }} - {{ .Description }}
func (c *Client) {{ .Name }}(ctx context.Context{{ range .Params }}, {{ .Name }} {{ goType .Type }}{{ end }}) ({{ if eq .Returns "one" }}*{{ .Model }}{{ else if eq .Returns "many" }}[]*{{ .Model }}{{ else }}error{{ end }}, error) {
	query := ` + "`" + `{{ .SQL }}` + "`" + `

	{{ if eq .Returns "exec" }}
	_, err := c.db.Exec(ctx, query{{ range .Params }}, {{ .Name }}{{ end }})
	return err
	{{ else if eq .Returns "one" }}
	var result {{ .Model }}
	err := c.db.QueryRow(ctx, query{{ range .Params }}, {{ .Name }}{{ end }}).Scan(
		// TODO: Add proper column scanning based on model
		&result,
	)
	if err != nil {
		return nil, err
	}
	return &result, nil
	{{ else if eq .Returns "many" }}
	rows, err := c.db.Query(ctx, query{{ range .Params }}, {{ .Name }}{{ end }})
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var results []*{{ .Model }}
	for rows.Next() {
		var result {{ .Model }}
		// TODO: Add proper column scanning based on model
		if err := rows.Scan(&result); err != nil {
			return nil, err
		}
		results = append(results, &result)
	}
	return results, rows.Err()
	{{ end }}
}
{{ end }}
`

	return g.executeTemplate("queries", "queries.go", tmpl, data)
}

func (g *Generator) executeTemplate(name, filename, tmplStr string, data interface{}) error {
	return g.executeTemplateToDir(g.outputDir, name, filename, tmplStr, data)
}

func (g *Generator) executeTemplateToDir(dir, name, filename, tmplStr string, data interface{}) error {
	funcMap := template.FuncMap{
		"toModelName":  toModelName,
		"toFieldName":  toFieldName,
		"toLower":      strings.ToLower,
		"hasUUID":      hasUUID,
		"slice":        slice,
		"add":          add,
		"hasPK":        hasPK,
		"len":          length,
		"goType":       goType,
	}

	tmpl, err := template.New(name).Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted code for debugging
		filePath := filepath.Join(dir, filename)
		return os.WriteFile(filePath, buf.Bytes(), 0644)
	}

	filePath := filepath.Join(dir, filename)
	return os.WriteFile(filePath, formatted, 0644)
}

// Helper functions

func toModelName(tableName string) string {
	return toCamelCase(tableName, true)
}

func toFieldName(columnName string) string {
	return toCamelCase(columnName, true)
}

func toCamelCase(s string, capitalize bool) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})

	for i, part := range parts {
		if i == 0 && !capitalize {
			parts[i] = strings.ToLower(part)
		} else {
			parts[i] = strings.Title(strings.ToLower(part))
		}
	}

	return strings.Join(parts, "")
}

func pluralize(s string) string {
	// Simple pluralization
	if strings.HasSuffix(s, "s") {
		return s + "es"
	}
	if strings.HasSuffix(s, "y") {
		return s[:len(s)-1] + "ies"
	}
	return s + "s"
}

func hasUUID(columns []*introspect.Column) bool {
	for _, col := range columns {
		if col.GoType == "uuid.UUID" {
			return true
		}
	}
	return false
}

func slice(s string, start, end int) string {
	return s[start:end]
}

func add(a, b int) int {
	return a + b
}

func hasPK(table *introspect.Table) bool {
	return table.PrimaryKey != nil && len(table.PrimaryKey.Columns) > 0
}

func length(s interface{}) int {
	switch v := s.(type) {
	case string:
		return len(v)
	case []*introspect.Column:
		return len(v)
	case []string:
		return len(v)
	default:
		return 0
	}
}

func goType(yamlType string) string {
	switch strings.ToLower(yamlType) {
	case "string":
		return "string"
	case "int", "int32":
		return "int32"
	case "int64":
		return "int64"
	case "float32":
		return "float32"
	case "float64":
		return "float64"
	case "bool", "boolean":
		return "bool"
	case "time":
		return "time.Time"
	case "uuid":
		return "uuid.UUID"
	default:
		return "interface{}"
	}
}
